FROM golang:1.25.2-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o /netflow-producer ./cmd/producer/main.go
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /netflow-producer .
CMD ["./netflow-producer"]